//
//  InventoryViewModel.swift
//  CigaretteCounter
//
//  Created by leeminwoo on 7/24/25.
//

import Foundation

class InventoryViewModel: ObservableObject {
    @Published var cigarettes: [Cigarette] = [
        Cigarette(name: "말보루 화이트", barcodeImageName: "product_001"),
        Cigarette(name: "말보루 비스타블라썸", barcodeImageName: "product_002"),
        Cigarette(name: "말보루 실버", barcodeImageName: "product_003"),
        Cigarette(name: "말보루 골드", barcodeImageName: "product_004"),
        Cigarette(name: "말보루 미디엄", barcodeImageName: "product_005"),
        Cigarette(name: "말보루 레드", barcodeImageName: "product_006"),
        Cigarette(name: "말보루 포레스트미스트", barcodeImageName: "product_007"),
        Cigarette(name: "말보루 가든 스플래시", barcodeImageName: "product_008"),
        Cigarette(name: "말보루 비스타 썸머", barcodeImageName: "product_009"),
        Cigarette(name: "말보루 비스타", barcodeImageName: "product_010"),
        Cigarette(name: "말보루 하이브리드 1", barcodeImageName: "product_011"),
        Cigarette(name: "말보루 하이브리드 5", barcodeImageName: "product_012"),
        Cigarette(name: "말보루 아이스블라스트", barcodeImageName: "product_013"),
        Cigarette(name: "말보루 아이스블라스트 1", barcodeImageName: "product_014"),
        Cigarette(name: "말보루 화이트후레시", barcodeImageName: "product_015"),
        Cigarette(name: "말보루 블랙 후래시", barcodeImageName: "product_016"),
        Cigarette(name: "말보루 비스타 트로피컬", barcodeImageName: "product_017"),
        Cigarette(name: "팔리아멘트 아쿠아 1", barcodeImageName: "product_018"),
        Cigarette(name: "팔리아멘트 아쿠아 3", barcodeImageName: "product_019"),
        Cigarette(name: "팔리아멘트 아쿠아 5", barcodeImageName: "product_020"),
        Cigarette(name: "팔리아멘트 하이브리드 1", barcodeImageName: "product_021"),
        Cigarette(name: "팔리아멘트 하이브리드 5", barcodeImageName: "product_022"),
        Cigarette(name: "팔리아멘트 수퍼슬림 레드", barcodeImageName: "product_023"),
        Cigarette(name: "버지니아 블루", barcodeImageName: "product_024"),
        Cigarette(name: "버지니아 골드", barcodeImageName: "product_025"),
        Cigarette(name: "하모니", barcodeImageName: "product_026"),
        Cigarette(name: "테리아 블랙루비", barcodeImageName: "product_027"),
        Cigarette(name: "테리아 블랙옐로우", barcodeImageName: "product_028"),
        Cigarette(name: "테리아 블랙퍼플", barcodeImageName: "product_029"),
        Cigarette(name: "테리아 퍼플웨이브", barcodeImageName: "product_030"),
        Cigarette(name: "테리아 썸머웨이브", barcodeImageName: "product_031"),
        Cigarette(name: "테리아 유젠", barcodeImageName: "product_032"),
        Cigarette(name: "테리아 썬펄", barcodeImageName: "product_033"),
        Cigarette(name: "테리아 오아시스 펄", barcodeImageName: "product_034"),
        Cigarette(name: "테리아 트와일라잇 펄", barcodeImageName: "product_035"),
        Cigarette(name: "센티아 실버", barcodeImageName: "product_036"),
        Cigarette(name: "센티아 그린", barcodeImageName: "product_037"),
        Cigarette(name: "센티아 골드", barcodeImageName: "product_038"),
        Cigarette(name: "센티아 퍼플", barcodeImageName: "product_039"),
        Cigarette(name: "테리아 블랙그린", barcodeImageName: "product_040"),
        Cigarette(name: "테리아 블루", barcodeImageName: "product_041"),
        Cigarette(name: "테리아 그린징", barcodeImageName: "product_042"),
        Cigarette(name: "테리아 그린", barcodeImageName: "product_043"),
        Cigarette(name: "테리아 앰버", barcodeImageName: "product_044"),
        Cigarette(name: "테리아 실버", barcodeImageName: "product_045"),
        Cigarette(name: "테리아 러셋", barcodeImageName: "product_046"),
        Cigarette(name: "테리아 티크", barcodeImageName: "product_047"),
        Cigarette(name: "테리아 아버 펄", barcodeImageName: "product_048"),
        Cigarette(name: "테리아 스탈링펄", barcodeImageName: "product_049"),
        Cigarette(name: "믹스 브린", barcodeImageName: "product_050"),
        Cigarette(name: "믹스 보나썸", barcodeImageName: "product_051"),
        Cigarette(name: "믹스 블루썸", barcodeImageName: "product_052"),
        Cigarette(name: "믹스 아이션", barcodeImageName: "product_053"),
        Cigarette(name: "믹스 믹스", barcodeImageName: "product_054"),
        Cigarette(name: "믹스 아이스", barcodeImageName: "product_055"),
        Cigarette(name: "믹스 프렌치", barcodeImageName: "product_056"),
        Cigarette(name: "믹스 아이스더블", barcodeImageName: "product_057"),
        Cigarette(name: "믹스 업투", barcodeImageName: "product_058"),
        Cigarette(name: "믹스 오라썸", barcodeImageName: "product_059"),
        Cigarette(name: "믹스 아이스뱅", barcodeImageName: "product_060"),
        Cigarette(name: "믹스 클래시", barcodeImageName: "product_061"),
        Cigarette(name: "믹스 콤보", barcodeImageName: "product_062"),
        Cigarette(name: "믹스 아이스모아", barcodeImageName: "product_063"),
        Cigarette(name: "핏 체인지 유니크", barcodeImageName: "product_064"),
        Cigarette(name: "핏 아이싱", barcodeImageName: "product_065"),
        Cigarette(name: "핏 체인지", barcodeImageName: "product_066"),
        Cigarette(name: "핏 체인지 업", barcodeImageName: "product_067"),
        Cigarette(name: "핏 체인지 큐", barcodeImageName: "product_068"),
        Cigarette(name: "핏 쿨 샷", barcodeImageName: "product_069"),
        Cigarette(name: "핏 스파키", barcodeImageName: "product_070"),
        Cigarette(name: "핏 아이시스트", barcodeImageName: "product_071"),
        Cigarette(name: "에임 리얼 카메오", barcodeImageName: "product_072"),
        Cigarette(name: "에임 리얼 시가리쉬", barcodeImageName: "product_073"),
        Cigarette(name: "그래뉼라 아이스러시", barcodeImageName: "product_074"),
        Cigarette(name: "에임 리얼 아이스 피크", barcodeImageName: "product_075"),
        Cigarette(name: "그래뉼라 트와이스", barcodeImageName: "product_076"),
        Cigarette(name: "그래뉼라 아이스노우", barcodeImageName: "product_077"),
        Cigarette(name: "그래뉼라 아이스", barcodeImageName: "product_078"),
        Cigarette(name: "그래뉼라 커플", barcodeImageName: "product_079"),
        Cigarette(name: "리얼 레귤러", barcodeImageName: "product_080"),
        Cigarette(name: "리얼 아이스", barcodeImageName: "product_081"),
        Cigarette(name: "에임 리얼 레귤러", barcodeImageName: "product_082"),
        Cigarette(name: "베이퍼스틱 트로피", barcodeImageName: "product_083"),
        Cigarette(name: "그래뉼라 블루밍", barcodeImageName: "product_084"),
        Cigarette(name: "베이퍼스틱 탱고", barcodeImageName: "product_085"),
        Cigarette(name: "리얼 써니스트", barcodeImageName: "product_086"),
        Cigarette(name: "그래뉼라 헤이즈", barcodeImageName: "product_087"),
        Cigarette(name: "에쎄 로열팰리스", barcodeImageName: "product_088"),
        Cigarette(name: "에쎄 골드리프", barcodeImageName: "product_089"),
        Cigarette(name: "에쎄 골드리프 1", barcodeImageName: "product_090"),
        Cigarette(name: "에쎄 골드리프 0.5", barcodeImageName: "product_091"),
        Cigarette(name: "에쎄 스페셜골드 1", barcodeImageName: "product_092"),
        Cigarette(name: "에쎄 스페셜골드 ", barcodeImageName: "product_093"),
        Cigarette(name: "에쎄 스페셜골드 0.5", barcodeImageName: "product_094"),
        Cigarette(name: "에쎄 체인지 린", barcodeImageName: "product_095"),
        Cigarette(name: "에쎄 체인지 그램", barcodeImageName: "product_096"),
        Cigarette(name: "에쎄 클래식", barcodeImageName: "product_097"),
        Cigarette(name: "에쎄 원", barcodeImageName: "product_098"),
        Cigarette(name: "에쎄 수", barcodeImageName: "product_099"),
        Cigarette(name: "에쎄 수 0.5", barcodeImageName: "product_100"),
        Cigarette(name: "에쎄 수 0.1", barcodeImageName: "product_101"),
        Cigarette(name: "에쎄 프라임", barcodeImageName: "product_102"),
        Cigarette(name: "에쎄 프레쏘", barcodeImageName: "product_103"),
        Cigarette(name: "에쎄 히말라야 윈터", barcodeImageName: "product_104"),
        Cigarette(name: "에쎄 아이스 1", barcodeImageName: "product_105"),
        Cigarette(name: "에쎄 이츠딥브라운", barcodeImageName: "product_106"),
        Cigarette(name: "에쎄 슈팅 레드", barcodeImageName: "product_107"),
        Cigarette(name: "에쎄 프로즌", barcodeImageName: "product_108"),
        Cigarette(name: "에쎄 히말라야", barcodeImageName: "product_109"),
        Cigarette(name: "에쎄 체인지 업", barcodeImageName: "product_110"),
        Cigarette(name: "에쎄 체인지 빙", barcodeImageName: "product_111"),
        Cigarette(name: "에쎄 체인지 w", barcodeImageName: "product_112"),
        Cigarette(name: "에쎄 체인지", barcodeImageName: "product_113"),
        Cigarette(name: "에쎄 체인지 4", barcodeImageName: "product_114"),
        Cigarette(name: "에쎄 느와르", barcodeImageName: "product_115"),
        Cigarette(name: "보헴 시가 마스터", barcodeImageName: "product_116"),
        Cigarette(name: "보헴 no 6", barcodeImageName: "product_117"),
        Cigarette(name: "보헴 no 3", barcodeImageName: "product_118"),
        Cigarette(name: "보헴 no 1", barcodeImageName: "product_119"),
        Cigarette(name: "쿠바나 더블", barcodeImageName: "product_120"),
        Cigarette(name: "쿠바나 샷", barcodeImageName: "product_121"),
        Cigarette(name: "보헴 시가리브레", barcodeImageName: "product_122"),
        Cigarette(name: "보헴 시가 미니 1", barcodeImageName: "product_123"),
        Cigarette(name: "보헴 시가 미니 5", barcodeImageName: "product_124"),
        Cigarette(name: "레종 블루", barcodeImageName: "product_125"),
        Cigarette(name: "레종 블랙", barcodeImageName: "product_126"),
        Cigarette(name: "레종 휘바 ice툰드라", barcodeImageName: "product_127"),
        Cigarette(name: "레종 프렌치 썸", barcodeImageName: "product_128"),
        Cigarette(name: "레종 휘바", barcodeImageName: "product_129"),
        Cigarette(name: "레종 프렌치블랙", barcodeImageName: "product_130"),
        Cigarette(name: "레종 요고", barcodeImageName: "product_131"),
        Cigarette(name: "레종 아이스블랑", barcodeImageName: "product_132"),
        Cigarette(name: "에쎄 센스", barcodeImageName: "product_133"),
        Cigarette(name: "시즌", barcodeImageName: "product_134"),
        Cigarette(name: "아이스볼트gt", barcodeImageName: "product_135"),
        Cigarette(name: "디스플러스", barcodeImageName: "product_136"),
        Cigarette(name: "디스", barcodeImageName: "product_137"),
        Cigarette(name: "클라우드 9", barcodeImageName: "product_138"),
        Cigarette(name: "클라우드 1", barcodeImageName: "product_139"),
        Cigarette(name: "슬림핏 브라운", barcodeImageName: "product_140"),
        Cigarette(name: "시가 아이스핏", barcodeImageName: "product_141"),
        Cigarette(name: "더원 블루", barcodeImageName: "product_142"),
        Cigarette(name: "더원 오렌지", barcodeImageName: "product_143"),
        Cigarette(name: "더원 화이트", barcodeImageName: "product_144"),
        Cigarette(name: "더원 체인지", barcodeImageName: "product_145"),
        Cigarette(name: "더원 임팩트", barcodeImageName: "product_146"),
        Cigarette(name: "아프리카 아이스잭", barcodeImageName: "product_147"),
        Cigarette(name: "아프리카 몰라", barcodeImageName: "product_148"),
        Cigarette(name: "아프리카 룰라", barcodeImageName: "product_149"),
        Cigarette(name: "타임 미드", barcodeImageName: "product_150"),
        Cigarette(name: "에쎄 엣지", barcodeImageName: "product_151"),
        Cigarette(name: "보헴 파이브", barcodeImageName: "product_152"),
        Cigarette(name: "보헴 카리브", barcodeImageName: "product_153"),
        Cigarette(name: "심플 에이스 1", barcodeImageName: "product_154"),
        Cigarette(name: "심플 클래식", barcodeImageName: "product_155"),
        Cigarette(name: "라일락", barcodeImageName: "product_156"),
        Cigarette(name: "한라산", barcodeImageName: "product_157"),
        Cigarette(name: "보헴 시가 시그니처", barcodeImageName: "product_158"),
        Cigarette(name: "보헴 파이프브리튼", barcodeImageName: "product_159"),
        Cigarette(name: "이오니아 핑크", barcodeImageName: "product_160"),
        Cigarette(name: "이오니아 그린", barcodeImageName: "product_161"),
        Cigarette(name: "이오니아 퍼플", barcodeImageName: "product_162"),
        Cigarette(name: "lbs 옐로우 3", barcodeImageName: "product_163"),
        Cigarette(name: "lbs 옐로우 1", barcodeImageName: "product_164"),
        Cigarette(name: "lbs 옐로우 맥스", barcodeImageName: "product_165"),
        Cigarette(name: "lbs 옐로우 수퍼슬림", barcodeImageName: "product_166"),
        Cigarette(name: "메비우스 롱스", barcodeImageName: "product_167"),
        Cigarette(name: "스카이블루(곽)", barcodeImageName: "product_168"),
        Cigarette(name: "스카이블루(팩)", barcodeImageName: "product_169"),
        Cigarette(name: "lss 윈드블루", barcodeImageName: "product_170"),
        Cigarette(name: "lss 원", barcodeImageName: "product_171"),
        Cigarette(name: "lbs 아이스스톰", barcodeImageName: "product_172"),
        Cigarette(name: "lbs 아이스피즈", barcodeImageName: "product_173"),
        Cigarette(name: "lbs 시트로웨이브", barcodeImageName: "product_174"),
        Cigarette(name: "lbs 선셋비치", barcodeImageName: "product_175"),
        Cigarette(name: "e 스타일6", barcodeImageName: "product_176"),
        Cigarette(name: "e 스타일 3", barcodeImageName: "product_177"),
        Cigarette(name: "lbs 믹스그린", barcodeImageName: "product_178"),
        Cigarette(name: "lbs 아이스바나", barcodeImageName: "product_179"),
        Cigarette(name: "lbs 스파클링듀", barcodeImageName: "product_180"),
        Cigarette(name: "lbs 퍼플", barcodeImageName: "product_181"),
        Cigarette(name: "lbs 트로피컬 믹스그린", barcodeImageName: "product_182"),
        Cigarette(name: "lbs 오리지널", barcodeImageName: "product_183"),
        Cigarette(name: "lbs 윈드블루", barcodeImageName: "product_184"),
        Cigarette(name: "카멜 파라다이스", barcodeImageName: "product_185"),
        Cigarette(name: "카멜 필터 8", barcodeImageName: "product_186"),
        Cigarette(name: "카멜필터 5", barcodeImageName: "product_187"),
        Cigarette(name: "뉴욕", barcodeImageName: "product_188"),
        Cigarette(name: "파리", barcodeImageName: "product_189"),
        Cigarette(name: "런던", barcodeImageName: "product_190"),
        Cigarette(name: "던힐 6", barcodeImageName: "product_191"),
        Cigarette(name: "던힐 3", barcodeImageName: "product_192"),
        Cigarette(name: "던힐 1", barcodeImageName: "product_193"),
        Cigarette(name: "던힐 파인컷 1mg", barcodeImageName: "product_194"),
        Cigarette(name: "던힐 프로스트", barcodeImageName: "product_195"),
        Cigarette(name: "던힐파인컷수프림", barcodeImageName: "product_196"),
        Cigarette(name: "던힐파인컷캡슐스위치", barcodeImageName: "product_197"),
        Cigarette(name: "던힐파인컷레인보우부스트", barcodeImageName: "product_198"),
        Cigarette(name: "던힐파인컷멜로우크러쉬", barcodeImageName: "product_199"),
        Cigarette(name: "던힐파인컷트로피컬크러쉬", barcodeImageName: "product_200"),
        Cigarette(name: "던힐파인컷0.1", barcodeImageName: "product_201"),
        Cigarette(name: "던힐파인커프로스트1", barcodeImageName: "product_202"),
        Cigarette(name: "던힐스위치6", barcodeImageName: "product_203"),
        Cigarette(name: "켄트더블프레쉬", barcodeImageName: "product_204"),
        Cigarette(name: "켄트0.5", barcodeImageName: "product_205"),
        Cigarette(name: "켄트1", barcodeImageName: "product_206"),
        Cigarette(name: "켄트블루", barcodeImageName: "product_207"),
        Cigarette(name: "켄트클릭", barcodeImageName: "product_208"),
        Cigarette(name: "켄트퍼플", barcodeImageName: "product_209"),
        Cigarette(name: "켄트스위치1", barcodeImageName: "product_210"),
        Cigarette(name: "에쎄쿨립스", barcodeImageName: "product_211"),
        Cigarette(name: "lbs믹스그린1ss", barcodeImageName: "product_212"),

    ]
    
    @Published var selectedCigarette: Cigarette?
    
    func resetAllCounts() {
        for index in cigarettes.indices {
            cigarettes[index].storefrontStock = 0
            cigarettes[index].warehouseStock = 0
            cigarettes[index].registeredStock = 0
        }
    }
} 